"""clean schema

Revision ID: 09ced478a115
Revises: a2a28aed535b
Create Date: 2026-07-27 22:13:05.116759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ced478a115'
down_revision: Union[str, Sequence[str], None] = 'a2a28aed535b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'npi_number')
    op.drop_column('users', 'specialty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('specialty', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('npi_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
