"""add remaining backend tables

Revision ID: 3edab533c783
Revises: adc9bd3076dd
Create Date: 2026-07-24 00:19:13.679054

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "3edab533c783"
down_revision: str | Sequence[str] | None = "adc9bd3076dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
