"""update user fields

Revision ID: 5826f91e3c57
Revises: 8eb1b4fb2b37
Create Date: 2026-07-23 12:08:53.235292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5826f91e3c57'
down_revision: Union[str, Sequence[str], None] = '8eb1b4fb2b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('users_org_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_column('users', 'name')
    op.drop_column('users', 'org_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_org_id_fkey'), 'users', 'organizations', ['org_id'], ['id'])
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'organization_id')
    # ### end Alembic commands ###
