"""create organizations users documents schema

Revision ID: 8eb1b4fb2b37
Revises: d8b12c8263e4
Create Date: 2026-07-23 11:45:52.804542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb1b4fb2b37'
down_revision: Union[str, Sequence[str], None] = 'd8b12c8263e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False))
    op.add_column('documents', sa.Column('file_s3_key', sa.String(length=500), nullable=False))
    op.add_column('documents', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('documents_sender_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by_user_id'], ['id'])
    op.drop_column('documents', 'file_name')
    op.drop_column('documents', 'sender_user_id')
    op.drop_column('documents', 's3_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('s3_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('sender_user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_sender_user_id_fkey'), 'documents', 'users', ['sender_user_id'], ['id'])
    op.drop_column('documents', 'original_filename')
    op.drop_column('documents', 'file_s3_key')
    op.drop_column('documents', 'uploaded_by_user_id')
    # ### end Alembic commands ###
