"""add remaining backend tables

Revision ID: adc9bd3076dd
Revises: d6e7d6f32458
Create Date: 2026-07-23 23:57:43.104388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc9bd3076dd'
down_revision: Union[str, Sequence[str], None] = 'd6e7d6f32458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('timezone', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('date_format', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('specialty', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('npi_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'npi_number')
    op.drop_column('users', 'specialty')
    op.drop_column('organizations', 'language')
    op.drop_column('organizations', 'date_format')
    op.drop_column('organizations', 'timezone')
    op.drop_column('organizations', 'type')
    # ### end Alembic commands ###
