"""update document table

Revision ID: d8b12c8263e4
Revises: b8615326979f
Create Date: 2026-07-22 23:13:57.610942

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d8b12c8263e4"
down_revision: str | Sequence[str] | None = "b8615326979f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
